### PR TITLE
Fix bug where mod download path is wrong

### PR DESCRIPTION
**Pull request by pswsm**
Related to issue #16 , since it still happened to me I decided to fix it.

Basically download a mod and get the path from steamcmd output.

### CODE REVIEW

**Comment by Raniz85** [comment]
This doesn't work for me (Gentoo Linux).

The path needs to be a `Path` or it won't work and if I wrap the return value from `extract_download_path` with `Path(match)` I still get an error about the file not being found.

**Comment by pswsm** [comment]
> This doesn't work for me (Gentoo Linux).
> 
> The path needs to be a `Path` or it won't work and if I wrap the return value from `extract_download_path` with `Path(match)` I still get an error about the file not being found.

@Raniz85 could you provide the output for me to review them?

**Comment by Spoons** [comment]
This is good work. You need to restore the PyPi parameters and then I will approve it after review.

**Comment by pswsm** [comment]
Okay, will do this night probs. I deleted them to release my own version in the meantime.

**Pull request closed without merging**
